### ISSUE TITLE
Error: can't edit 24-bit torrent - skipping: no control matching name 'bitrate'

### ISSUE THREAD

**Issue by SavageCore** [aktavor69/pthbetter#20]
The following release produces the error `Error: can't edit 24-bit torrent - skipping: no control matching name 'bitrate'`

torrents.php?id=302022&torrentid=579693#torrent579693

**Comment by SavageCore** [comment]
Should be fixed in PR #21

**Comment by animeai** [comment]
Just did a git pull but still getting this error... 

Example:
Release found: Noxkult (2015)
Release URL: https://passtheheadphones.me/torrents.php?id=212860&torrentid=391098#torrent391098
Marking release as 24bit lossless.
Error: can't edit 24-bit torrent - skipping: no control matching name 'bitrate'

**Comment by SavageCore** [comment]
@animeai what user class are you? I think the index of which form must be changing..

**Comment by animeai** [comment]
I'm elite

**Comment by SavageCore** [comment]
Hmm also Elite...

@aktavor69 what do you think?
